<?php

namespace ContainerAiYbjj7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Books\Application\Delete\DeleteBook' shared autowired service.
     *
     * @return \App\Books\Application\Delete\DeleteBook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Books/Application/Delete/DeleteBook.php';
        include_once \dirname(__DIR__, 4).'/src/Books/Application/Delete/DeleteFile.php';

        return $container->privates['App\\Books\\Application\\Delete\\DeleteBook'] = new \App\Books\Application\Delete\DeleteBook(($container->privates['App\\Books\\Infrastructure\\Persistence\\DoctrineBookRepository'] ?? $container->load('getDoctrineBookRepositoryService')), new \App\Books\Application\Delete\DeleteFile(($container->privates['default.storage'] ?? $container->load('getDefault_StorageService'))), ($container->privates['App\\Books\\Application\\Find\\BookFinder'] ?? $container->load('getBookFinderService')));
    }
}
