<?php

namespace ContainerAiYbjj7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetBookInfoByIsbnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.J7QwkVN.App\Service\Isbn\GetBookInfoByIsbn' shared service.
     *
     * @return \App\Service\Isbn\GetBookInfoByIsbn
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.J7QwkVN": it references class "App\\Service\\Isbn\\GetBookInfoByIsbn" but no such service exists.');
    }
}
