<?php

namespace ContainerWjxafvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UuqYgfNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uuqYgfN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uuqYgfN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Authors\\Infrastructure\\Controllers\\AuthorController::post' => ['privates', '.service_locator.O7oC5Tw', 'get_ServiceLocator_O7oC5TwService', true],
            'App\\Controller\\Api\\BooksController::delete' => ['privates', '.service_locator.6v5173m', 'get_ServiceLocator_6v5173mService', true],
            'App\\Controller\\Api\\BooksController::get' => ['privates', '.service_locator.ytoqIvb', 'get_ServiceLocator_YtoqIvbService', true],
            'App\\Controller\\Api\\BooksController::getById' => ['privates', '.service_locator.5JZAmNe', 'get_ServiceLocator_5JZAmNeService', true],
            'App\\Controller\\Api\\BooksController::patch' => ['privates', '.service_locator.sSxl1Xf', 'get_ServiceLocator_SSxl1XfService', true],
            'App\\Controller\\Api\\BooksController::post' => ['privates', '.service_locator.v79vB3N', 'get_ServiceLocator_V79vB3NService', true],
            'App\\Controller\\Api\\BooksController::put' => ['privates', '.service_locator.ydyMSjM', 'get_ServiceLocator_YdyMSjMService', true],
            'App\\Controller\\Api\\IsbnController::get' => ['privates', '.service_locator.J7QwkVN', 'get_ServiceLocator_J7QwkVNService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Authors\\Infrastructure\\Controllers\\AuthorController:post' => ['privates', '.service_locator.O7oC5Tw', 'get_ServiceLocator_O7oC5TwService', true],
            'App\\Controller\\Api\\BooksController:delete' => ['privates', '.service_locator.6v5173m', 'get_ServiceLocator_6v5173mService', true],
            'App\\Controller\\Api\\BooksController:get' => ['privates', '.service_locator.ytoqIvb', 'get_ServiceLocator_YtoqIvbService', true],
            'App\\Controller\\Api\\BooksController:getById' => ['privates', '.service_locator.5JZAmNe', 'get_ServiceLocator_5JZAmNeService', true],
            'App\\Controller\\Api\\BooksController:patch' => ['privates', '.service_locator.sSxl1Xf', 'get_ServiceLocator_SSxl1XfService', true],
            'App\\Controller\\Api\\BooksController:post' => ['privates', '.service_locator.v79vB3N', 'get_ServiceLocator_V79vB3NService', true],
            'App\\Controller\\Api\\BooksController:put' => ['privates', '.service_locator.ydyMSjM', 'get_ServiceLocator_YdyMSjMService', true],
            'App\\Controller\\Api\\IsbnController:get' => ['privates', '.service_locator.J7QwkVN', 'get_ServiceLocator_J7QwkVNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Authors\\Infrastructure\\Controllers\\AuthorController::post' => '?',
            'App\\Controller\\Api\\BooksController::delete' => '?',
            'App\\Controller\\Api\\BooksController::get' => '?',
            'App\\Controller\\Api\\BooksController::getById' => '?',
            'App\\Controller\\Api\\BooksController::patch' => '?',
            'App\\Controller\\Api\\BooksController::post' => '?',
            'App\\Controller\\Api\\BooksController::put' => '?',
            'App\\Controller\\Api\\IsbnController::get' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Authors\\Infrastructure\\Controllers\\AuthorController:post' => '?',
            'App\\Controller\\Api\\BooksController:delete' => '?',
            'App\\Controller\\Api\\BooksController:get' => '?',
            'App\\Controller\\Api\\BooksController:getById' => '?',
            'App\\Controller\\Api\\BooksController:patch' => '?',
            'App\\Controller\\Api\\BooksController:post' => '?',
            'App\\Controller\\Api\\BooksController:put' => '?',
            'App\\Controller\\Api\\IsbnController:get' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
