<?php

namespace ContainerWjxafvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooksFinderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Book\BooksFinder' shared autowired service.
     *
     * @return \App\Service\Book\BooksFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Book/BooksFinder.php';

        return $container->privates['App\\Service\\Book\\BooksFinder'] = new \App\Service\Book\BooksFinder(($container->privates['App\\Repository\\BookRepository'] ?? $container->load('getBookRepositoryService')));
    }
}
