<?php

namespace ContainerWjxafvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookFieldUpdaterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Book\BookFieldUpdater' shared autowired service.
     *
     * @return \App\Service\Book\BookFieldUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\Book\\BookFieldUpdater": argument "$bookFinder" of method "__construct()" references class "App\\Service\\Book\\bookFinder" but no such service exists. Did you mean "App\\Service\\Book\\BookFinder"?');
    }
}
