<?php

namespace ContainerWjxafvU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Book\DeleteBook' shared autowired service.
     *
     * @return \App\Service\Book\DeleteBook
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Book/DeleteBook.php';
        include_once \dirname(__DIR__, 4).'/src/Service/DeleteFile.php';

        return $container->privates['App\\Service\\Book\\DeleteBook'] = new \App\Service\Book\DeleteBook(($container->privates['App\\Repository\\BookRepository'] ?? $container->load('getBookRepositoryService')), new \App\Service\DeleteFile(($container->privates['default.storage'] ?? $container->load('getDefault_StorageService'))), ($container->privates['App\\Service\\Book\\BookFinder'] ?? $container->load('getBookFinderService')));
    }
}
