<?php

namespace ContainerOwQxRio;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryFinderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Categories\Application\Find\CategoryFinder' shared autowired service.
     *
     * @return \App\Categories\Application\Find\CategoryFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Categories/Application/Find/CategoryFinder.php';

        return $container->privates['App\\Categories\\Application\\Find\\CategoryFinder'] = new \App\Categories\Application\Find\CategoryFinder(($container->privates['App\\Categories\\Infrastructure\\Persistence\\DoctrineCategoryRepository'] ?? $container->load('getDoctrineCategoryRepositoryService')));
    }
}
