<?php

namespace ContainerOwQxRio;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateBookCategoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Books\Application\Update\UpdateBookCategory' shared autowired service.
     *
     * @return \App\Books\Application\Update\UpdateBookCategory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Books/Application/Update/UpdateBookCategory.php';

        return $container->privates['App\\Books\\Application\\Update\\UpdateBookCategory'] = new \App\Books\Application\Update\UpdateBookCategory(($container->privates['App\\Categories\\Application\\Find\\CategoryFinder'] ?? $container->load('getCategoryFinderService')), ($container->privates['App\\Categories\\Application\\Create\\CategoryCreator'] ?? $container->load('getCategoryCreatorService')));
    }
}
