author_controller_get:
    path: /api/author
    controller: App\Authors\Infrastructure\Controllers\AuthorsGetController
    methods:  [GET] 

author_controller_post:
    path: /api/author
    controller: App\Authors\Infrastructure\Controllers\AuthorsPostController
    methods:  [POST] 