<?php

namespace Container3hvB4Ye;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookCreatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Books\Application\Create\BookCreator' shared autowired service.
     *
     * @return \App\Books\Application\Create\BookCreator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Books/Application/Create/BookCreator.php';

        return $container->privates['App\\Books\\Application\\Create\\BookCreator'] = new \App\Books\Application\Create\BookCreator(($container->privates['App\\Books\\Application\\UploadFile\\BookFileUploader'] ?? $container->load('getBookFileUploaderService')), ($container->privates['App\\Books\\Infrastructure\\Persistence\\DoctrineBookRepository'] ?? $container->load('getDoctrineBookRepositoryService')), ($container->privates['App\\Authors\\Application\\Find\\AuthorFinder'] ?? $container->load('getAuthorFinderService')), ($container->privates['App\\Shared\\Infrastructure\\Event\\RabbitMqEventBus'] ?? $container->load('getRabbitMqEventBusService')));
    }
}
