<?php

namespace Container3hvB4Ye;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XtLJX52.Symfony\Component\Validator\Constraints\Collection' shared service.
     *
     * @return \Symfony\Component\Validator\Constraints\Collection
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XtLJX52": it references class "Symfony\\Component\\Validator\\Constraints\\Collection" but no such service exists.');
    }
}
