<?php

namespace Container3hvB4Ye;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRabbitMqEventBusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Event\RabbitMqEventBus' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Event\RabbitMqEventBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Domain/Event/EventBus.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Event/RabbitMqEventBus.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\Shared\\Infrastructure\\Event\\RabbitMqEventBus'])) {
            return $container->privates['App\\Shared\\Infrastructure\\Event\\RabbitMqEventBus'];
        }

        return $container->privates['App\\Shared\\Infrastructure\\Event\\RabbitMqEventBus'] = new \App\Shared\Infrastructure\Event\RabbitMqEventBus($a);
    }
}
