<?php

namespace Container3hvB4Ye;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSymfonyCommandBusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Bus\SymfonyCommandBus' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Bus\SymfonyCommandBus
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Domain/Bus/CommandBus.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Bus/SymfonyCommandBus.php';

        $a = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\Shared\\Infrastructure\\Bus\\SymfonyCommandBus'])) {
            return $container->privates['App\\Shared\\Infrastructure\\Bus\\SymfonyCommandBus'];
        }

        return $container->privates['App\\Shared\\Infrastructure\\Bus\\SymfonyCommandBus'] = new \App\Shared\Infrastructure\Bus\SymfonyCommandBus($a);
    }
}
