App\Authors\Domain\Author:
    type: entity
    table: author
    repositoryClass: App\Authors\Infrastructure\Persistence\DoctrineAuthorRepository
    id:
        id:
            type: string
            scale: null
            length: null
            unique: false
            nullable: false
            precision: null
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: null
            length: 255
            unique: false
            nullable: true
            precision: null
    oneToMany:
        books:
            targetEntity: App\Books\Domain\Book
            cascade: {  }
            fetch: LAZY
            mappedBy: author
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
