<?php

namespace ContainerLw4z37C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteFileService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Books\Application\Delete\DeleteFile' shared autowired service.
     *
     * @return \App\Books\Application\Delete\DeleteFile
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Books/Application/Delete/DeleteFile.php';

        return $container->privates['App\\Books\\Application\\Delete\\DeleteFile'] = new \App\Books\Application\Delete\DeleteFile(($container->privates['default.storage'] ?? $container->load('getDefault_StorageService')));
    }
}
