<?php

namespace ContainerR4CXhpr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteAuthorOnBookDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Authors\Application\Delete\DeleteAuthorOnBookDelete' shared autowired service.
     *
     * @return \App\Authors\Application\Delete\DeleteAuthorOnBookDelete
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Authors/Application/Delete/DeleteAuthorOnBookDelete.php';

        return $container->privates['App\\Authors\\Application\\Delete\\DeleteAuthorOnBookDelete'] = new \App\Authors\Application\Delete\DeleteAuthorOnBookDelete(($container->privates['App\\Authors\\Application\\Delete\\DeleteAuthor'] ?? $container->load('getDeleteAuthorService')), ($container->privates['App\\Authors\\Application\\Find\\AuthorFinder'] ?? $container->load('getAuthorFinderService')));
    }
}
