<?php

namespace ContainerR4CXhpr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteFileOnBookDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Shared\Application\DeleteFileOnBookDelete' shared autowired service.
     *
     * @return \App\Shared\Application\DeleteFileOnBookDelete
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Application/DeleteFileOnBookDelete.php';

        return $container->privates['App\\Shared\\Application\\DeleteFileOnBookDelete'] = new \App\Shared\Application\DeleteFileOnBookDelete(($container->privates['App\\Shared\\Application\\DeleteFile'] ?? $container->load('getDeleteFileService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
