<?php

namespace ContainerXk6oCGK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiKeyAuthenticatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Security\ApiKeyAuthenticator' shared autowired service.
     *
     * @return \App\Security\ApiKeyAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/src/Security/ApiKeyAuthenticator.php';

        return $container->privates['App\\Security\\ApiKeyAuthenticator'] = new \App\Security\ApiKeyAuthenticator($container->getEnv('resolve:APP_API_TOKEN'));
    }
}
