<?php

namespace ContainerXk6oCGK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIsbnControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Isbn\Intrastructure\Controllers\IsbnController' shared autowired service.
     *
     * @return \App\Isbn\Intrastructure\Controllers\IsbnController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Isbn/Intrastructure/Controllers/IsbnController.php';

        $container->services['App\\Isbn\\Intrastructure\\Controllers\\IsbnController'] = $instance = new \App\Isbn\Intrastructure\Controllers\IsbnController();

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Isbn\\Intrastructure\\Controllers\\IsbnController', $container));

        return $instance;
    }
}
