<?php

namespace ContainerD829y5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookCreatedDomainEventDecoderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Event\BookCreatedDomainEventDecoder' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Event\BookCreatedDomainEventDecoder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Event/BookCreatedDomainEventDecoder.php';

        return $container->privates['App\\Shared\\Infrastructure\\Event\\BookCreatedDomainEventDecoder'] = new \App\Shared\Infrastructure\Event\BookCreatedDomainEventDecoder();
    }
}
