<?php

namespace ContainerD829y5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAuthorCommandHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Authors\Application\Create\CreateAuthorCommandHandler' shared autowired service.
     *
     * @return \App\Authors\Application\Create\CreateAuthorCommandHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Authors/Application/Create/CreateAuthorCommandHandler.php';

        return $container->privates['App\\Authors\\Application\\Create\\CreateAuthorCommandHandler'] = new \App\Authors\Application\Create\CreateAuthorCommandHandler(($container->privates['App\\Authors\\Application\\Create\\AuthorCreator'] ?? $container->load('getAuthorCreatorService')));
    }
}
