<?php

namespace ContainerD829y5S;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\BookFileUploader\Application\BookFileUploader' shared autowired service.
     *
     * @return \App\Books\Application\UploadFile\BookFileUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/FileUploader/Application/BookFileUploader.php';

        return $container->privates['App\\Books\\Application\\UploadFile\\BookFileUploader'] = new \App\Books\Application\UploadFile\BookFileUploader(($container->privates['App\\Books\\Infrastructure\\Uploaders\\S3BookFileUploader'] ?? $container->load('getS3FileUploaderService')));
    }
}
