<?php

namespace ContainerD829y5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetBookInfoByIsbnService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Isbn\Application\GetBookInfoByIsbn' shared autowired service.
     *
     * @return \App\Isbn\Application\GetBookInfoByIsbn
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Isbn/Application/GetBookInfoByIsbn.php';

        return $container->privates['App\\Isbn\\Application\\GetBookInfoByIsbn'] = new \App\Isbn\Application\GetBookInfoByIsbn(($container->privates['App\\Shared\\Infrastructure\\Symfony\\HttpClient'] ?? $container->load('getHttpClientService')));
    }
}
