<?php

namespace ContainerD829y5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHttpClientService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Shared\Infrastructure\Symfony\HttpClient' shared autowired service.
     *
     * @return \App\Shared\Infrastructure\Symfony\HttpClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Symfony/HttpClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Symfony/HttpClient.php';

        return $container->privates['App\\Shared\\Infrastructure\\Symfony\\HttpClient'] = new \App\Shared\Infrastructure\Symfony\HttpClient(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
