<?php

namespace ContainerD829y5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_AmqpService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.transport.amqp' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Receiver/ReceiverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Sender/SenderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Serialization/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Shared/Infrastructure/Event/DomainEventJsonSerializer.php';

        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.amqp'])) {
            return $container->privates['messenger.transport.amqp'];
        }

        return $container->privates['messenger.transport.amqp'] = $a->createTransport($container->getEnv('MESSENGER_TRANSPORT_DSN'), ['exchange' => ['name' => 'exchange_librarify', 'type' => 'topic'], 'queues' => [], 'transport_name' => 'amqp'], ($container->privates['serializer.amqp'] ??= new \App\Shared\Infrastructure\Event\DomainEventJsonSerializer()));
    }
}
