<?php

namespace ContainerD829y5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Event_Async_Messenger_HandlersLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.bus.event.async.messenger.handlers_locator' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlersLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        return $container->privates['messenger.bus.event.async.messenger.handlers_locator'] = new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\Authors\\Application\\Create\\CreateAuthorCommand' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.Ws8ygZl'] ?? $container->load('get_Messenger_HandlerDescriptor_Ws8ygZlService'));
        }, 1), 'App\\Books\\Domain\\BookCreatedDomainEvent' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.iUbUdby'] ?? $container->load('get_Messenger_HandlerDescriptor_IUbUdbyService'));
        }, 1), 'Symfony\\Component\\Process\\Messenger\\RunProcessMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.L2fkoWL'] ?? $container->load('get_Messenger_HandlerDescriptor_L2fkoWLService'));
        }, 1), 'Symfony\\Component\\Console\\Messenger\\RunCommandMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.JatrBkD'] ?? $container->load('get_Messenger_HandlerDescriptor_JatrBkDService'));
        }, 1), 'Symfony\\Component\\HttpClient\\Messenger\\PingWebhookMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.6HAAYMY'] ?? $container->load('get_Messenger_HandlerDescriptor_6HAAYMYService'));
        }, 1), 'Symfony\\Component\\Messenger\\Message\\RedispatchMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.N0_CLe0'] ?? $container->load('get_Messenger_HandlerDescriptor_N0CLe0Service'));
        }, 1)]);
    }
}
