<?php

namespace ContainerD829y5S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_ReceiverLocatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'messenger.receiver_locator' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['messenger.receiver_locator'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'amqp' => ['privates', 'messenger.transport.amqp', 'getMessenger_Transport_AmqpService', true],
            'librarify_book_created_subscriber' => ['privates', 'messenger.transport.librarify_book_created_subscriber', 'getMessenger_Transport_LibrarifyBookCreatedSubscriberService', true],
            'messenger.transport.amqp' => ['privates', 'messenger.transport.amqp', 'getMessenger_Transport_AmqpService', true],
            'messenger.transport.librarify_book_created_subscriber' => ['privates', 'messenger.transport.librarify_book_created_subscriber', 'getMessenger_Transport_LibrarifyBookCreatedSubscriberService', true],
        ], [
            'amqp' => '?',
            'librarify_book_created_subscriber' => '?',
            'messenger.transport.amqp' => '?',
            'messenger.transport.librarify_book_created_subscriber' => '?',
        ]);
    }
}
