<?php

namespace ContainerD829y5S;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getS3FileUploaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\BookFileUploader\Infrastructure\S3BookFileUploader' shared autowired service.
     *
     * @return \App\BookFileUploader\Infrastructure\S3BookFileUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/BookFileUploader/Domain/BookFileUploaderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/BookFileUploader/Infrastructure/S3BookFileUploader.php';

        return $container->privates['App\\Books\\Infrastructure\\Uploaders\\S3BookFileUploader'] = new \App\Books\Infrastructure\Uploader\S3BookFileUploader(($container->privates['default.storage'] ?? $container->load('getDefault_StorageService')));
    }
}
