<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJhKsxP\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJhKsxP/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXJhKsxP.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXJhKsxP\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXJhKsxP\App_KernelTestDebugContainer([
    'container.build_hash' => 'XJhKsxP',
    'container.build_id' => 'f110f81a',
    'container.build_time' => 1710010355,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJhKsxP');
