<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD829y5S\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD829y5S/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerD829y5S.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerD829y5S\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerD829y5S\App_KernelTestDebugContainer([
    'container.build_hash' => 'D829y5S',
    'container.build_id' => '95cb0003',
    'container.build_time' => 1711203909,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD829y5S');
