<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLw4z37C\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLw4z37C/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerLw4z37C.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerLw4z37C\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerLw4z37C\App_KernelTestDebugContainer([
    'container.build_hash' => 'Lw4z37C',
    'container.build_id' => '4864c53d',
    'container.build_time' => 1709205799,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLw4z37C');
