<?php

namespace ContainerKCpyeHu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5JZAmNeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5JZAmNe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5JZAmNe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bookFinder' => ['privates', 'App\\Service\\Book\\BookFinder', 'getBookFinderService', true],
        ], [
            'bookFinder' => 'App\\Service\\Book\\BookFinder',
        ]);
    }
}
