<?php

namespace ContainerKCpyeHu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Authors\Infrastructure\Controllers\AuthorController' shared autowired service.
     *
     * @return \App\Authors\Infrastructure\Controllers\AuthorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Authors/Infrastructure/Controllers/AuthorController.php';

        $container->services['App\\Authors\\Infrastructure\\Controllers\\AuthorController'] = $instance = new \App\Authors\Infrastructure\Controllers\AuthorController(($container->privates['App\\Authors\\Infrastructure\\Persistence\\DoctrineAuthorRepository'] ?? $container->load('getDoctrineAuthorRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Authors\\Infrastructure\\Controllers\\AuthorController', $container));

        return $instance;
    }
}
