<?php

namespace ContainerKCpyeHu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploaderS3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FileUploader\FileUploaderS3' shared autowired service.
     *
     * @return \App\Service\FileUploader\FileUploaderS3
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Interfaces/FileUploaderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileUploader/FileUploaderS3.php';

        return $container->privates['App\\Service\\FileUploader\\FileUploaderS3'] = new \App\Service\FileUploader\FileUploaderS3(($container->privates['default.storage'] ?? $container->load('getDefault_StorageService')));
    }
}
