<?php

namespace ContainerKCpyeHu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetBookInfoByIsbnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Isbn\GetBookInfoByIsbn' shared autowired service.
     *
     * @return \App\Service\Isbn\GetBookInfoByIsbn
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Isbn/GetBookInfoByIsbn.php';
        include_once \dirname(__DIR__, 4).'/src/Interfaces/HttpClientInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Utils/HttpClient.php';

        return $container->privates['App\\Service\\Isbn\\GetBookInfoByIsbn'] = new \App\Service\Isbn\GetBookInfoByIsbn(new \App\Service\Utils\HttpClient(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container))));
    }
}
