<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRw0xpQo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRw0xpQo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRw0xpQo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRw0xpQo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRw0xpQo\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rw0xpQo',
    'container.build_id' => '11267cfb',
    'container.build_time' => 1709205931,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRw0xpQo');
