<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLq1gUKi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLq1gUKi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLq1gUKi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLq1gUKi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLq1gUKi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lq1gUKi',
    'container.build_id' => '828b53de',
    'container.build_time' => 1709213588,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLq1gUKi');
