<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'author_controller_get' => [[], ['_controller' => 'App\\Authors\\Infrastructure\\Controllers\\AuthorsGetController'], [], [['text', '/api/author']], [], [], []],
    'author_controller_post' => [[], ['_controller' => 'App\\Authors\\Infrastructure\\Controllers\\AuthorsPostController'], [], [['text', '/api/author']], [], [], []],
    'author_controller_delete' => [['id'], ['_controller' => 'App\\Authors\\Infrastructure\\Controllers\\AuthorsDeleteController'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/author']], [], [], []],
    'book_controller_get' => [[], ['_controller' => 'App\\Books\\Infrastructure\\Controllers\\BooksGetController'], [], [['text', '/api/books']], [], [], []],
    'book_controller_get_id' => [['id'], ['_controller' => 'App\\Books\\Infrastructure\\Controllers\\BookGetController'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'book_controller_post' => [[], ['_controller' => 'App\\Books\\Infrastructure\\Controllers\\BooksPostController'], [], [['text', '/api/book']], [], [], []],
    'book_controller_edit' => [['id'], ['_controller' => 'App\\Books\\Infrastructure\\Controllers\\BooksPutController'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book']], [], [], []],
    'book_controller_delete' => [['id'], ['_controller' => 'App\\Books\\Infrastructure\\Controllers\\BooksDeleteController'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book']], [], [], []],
    'book_controller_patch' => [['id'], ['_controller' => 'App\\Books\\Infrastructure\\Controllers\\BooksPatchController'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/book']], [], [], []],
    'isbn_controller_get' => [[], ['_controller' => 'App\\Isbn\\Intrastructure\\Controllers\\IsbnGetController'], [], [['text', '/api/isbn']], [], [], []],
];
